<a href="https://colab.research.google.com/github/Calvin-CS344-21SP/ai-portfolio-epigeneticschick/blob/main/Copy_of_007_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# `007-softmax`

Task: practice using the `softmax` function.

## Setup

In [ ]:
import torch
from torch import tensor
import matplotlib.pyplot as plt
%matplotlib inline

## Task

Let's see how `softmax` behaves!

Try this example: `x = tensor([1., 2., 3.])`

1. Compare the result of `softmax(x)` with the result of `x.exp() / x.exp().sum()`. Are they close? They are the exact same.
2. What happens to the output of `softmax` when you give it `x + 1` instead of `x`? What happens if you add 100 instead? (Do this without changing `x`) It does not change. 
3. *optional*: What happens to the output of `x.exp() / x.exp().sum()` when you add 1 to x? When you add 100? 
4. What happens when you multiply `x` by a constant like 0.5 or 3.0 before passing it to `softmax`? Compare this situation with the situation in question 2. The answer is much different. The situation is different because rather than maintaining their distant numerically. The distance could possibly grow due to the fact that it has been mutiplied 

**Note: you'll need to specify the axis: `torch.softmax(x, dim=0)`.**

## Solution

Add code and Markdown cells for each of the listed tasks above.

In [ ]:
x = tensor([1.,2.,3.])

In [ ]:
print(torch.softmax(x, dim=0))
print(x.exp()/x.exp().sum())

tensor([0.0900, 0.2447, 0.6652])
tensor([0.0900, 0.2447, 0.6652])


In [ ]:
print(torch.softmax(x+1,dim=0))
print(torch.softmax(x+100,dim=0))

tensor([0.0900, 0.2447, 0.6652])
tensor([0.0900, 0.2447, 0.6652])


In [ ]:
new_x = x *3.5
print(torch.softmax(new_x, dim=0))


tensor([8.8437e-04, 2.9286e-02, 9.6983e-01])


## Analysis

In [ ]:
x2 = tensor([1., 0.,])
x3 = x2 - 1
x3

tensor([ 0., -1.])

In [ ]:
x4 = x2 * 2
x4

tensor([2., 0.])

In [ ]:
print(torch.softmax(x2, dim=0))
print(torch.softmax(x3, dim=0))
print(torch.softmax(x4, dim=0))

tensor([0.7311, 0.2689])
tensor([0.7311, 0.2689])
tensor([0.8808, 0.1192])


1. Are `softmax(x2)` and `softmax(x3)` the same or different? How could you tell without having to try it? They are the same. I could tell because one is being subtracted from x2 to make x3 meaning that they maintain their distance. 
2. Are `softmax(x2)` and `softmax(x4)` the same or different? How could you tell without having to try it? They are different, becuase x4 is x2 mutiplied by a constant. Mutiplication by a constant alters the distance between numbers in the tensors. 

## Extension *optional*

1. Try to prove your observation in \#2 by symbolically simplifying the expression `softmax(logits + c)` and seeing if you can get `softmax(logits)`. Remember that `softmax(x) = exp(x) / exp(x).sum()` and `exp(a + b) = exp(a)exp(b)`.

2. Why does `exp(x + 100) / exp(x + 100).sum()` not work, while it does work for `torch.softmax`? Can you think of what `torch.softmax` might be doing to make sure that works?